#
# Makefile for the Linux kernel device drivers.
#
obj-y				+= proxm_class/
obj-n				+= adux-1020/
obj-n				+= cm32180/
obj-n				+= cm36283/
obj-n				+= cm3628/
obj-n				+= al3010/
obj-n				+= stk3210/
#obj-n				+= proximity/
#obj-n              	+= cap1106/
obj-y				+=IRsensor/