#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
# sensor drivers
obj-y  += hall/
# ASUS_BSP +++ Peter_Lu "KXTJ9 Gsensor & E-compass"
obj-$(CONFIG_SENSORS_AK09911)  += akm09911/
obj-$(CONFIG_SENSORS_KXTJ9)    += kxtj9/
# ASUS_BSP --- Peter_Lu "KXTJ9 Gsensor & E-compass"
